server:
    port: 8443
    ssl:
        enabled: true
        key-store: "server.keystore.jks"
        key-store-password: javaexample
com:
    yoti:
        client:
            clientSdkId: "sdk-id-from-dashboard"
            accessSecurityKey: "classpath:/local-access-security.pem"
        applicationId: "app-id-from-dashboard"